export const GET_REPOSITORY_LIST = 'GET_REPOSITORY_LIST';
export type GET_REPOSITORY_LIST = typeof GET_REPOSITORY_LIST;

export const GET_REPOSITORY_SUCCESS = 'GET_REPOSITORY_SUCCESS';
export type GET_REPOSITORY_SUCCESS = typeof GET_REPOSITORY_SUCCESS;

export const GET_REPOSITORY_FAILURE = 'GET_REPOSITORY_FAILURE';
export type GET_REPOSITORY_FAILURE = typeof GET_REPOSITORY_FAILURE;

export const SHOW_CREATE_REPOSITORY_MODAL = 'SHOW_CREATE_REPOSITORY_MODAL';
export type SHOW_CREATE_REPOSITORY_MODAL = typeof SHOW_CREATE_REPOSITORY_MODAL;

export const HIDE_CREATE_REPOSITORY_MODAL = 'HIDE_CREATE_REPOSITORY_MODAL';
export type HIDE_CREATE_REPOSITORY_MODAL = typeof HIDE_CREATE_REPOSITORY_MODAL;

export const CREATE_REPOSITORY_START = 'CREATE_REPOSITORY_START';
export type CREATE_REPOSITORY_START = typeof CREATE_REPOSITORY_START;

export const CREATE_REPOSITORY_SUCCESS = 'CREATE_REPOSITORY_SUCCESS';
export type CREATE_REPOSITORY_SUCCESS = typeof CREATE_REPOSITORY_SUCCESS;

export const CREATE_REPOSITORY_FAILURE = 'CREATE_REPOSITORY_FAILURE';
export type CREATE_REPOSITORY_FAILURE = typeof CREATE_REPOSITORY_FAILURE;

export const DELETE_REPOSITORY_START = 'DELETE_REPOSITORY_START';
export type DELETE_REPOSITORY_START = typeof DELETE_REPOSITORY_START;

export const DELETE_REPOSITORY_SUCCESS = 'DELETE_REPOSITORY_SUCCESS';
export type DELETE_REPOSITORY_SUCCESS = typeof DELETE_REPOSITORY_SUCCESS;

export const DELETE_REPOSITORY_FAILURE = 'DELETE_REPOSITORY_FAILURE';
export type DELETE_REPOSITORY_FAILURE = typeof DELETE_REPOSITORY_FAILURE;