export const GET_REPOSITORY_LIST = 'GET_REPOSITORY_LIST';
export type GET_REPOSITORY_LIST = typeof GET_REPOSITORY_LIST;

export const GET_REPOSITORY_SUCCESS = 'GET_REPOSITORY_SUCCESS';
export type GET_REPOSITORY_SUCCESS = typeof GET_REPOSITORY_SUCCESS;

export const GET_REPOSITORY_FAILURE = 'GET_REPOSITORY_FAILURE';
export type GET_REPOSITORY_FAILURE = typeof GET_REPOSITORY_FAILURE;