language: node_js
node_js:
  - 14

services:
  - docker

install:
  - npm ci

script:
  - CI=false npm run build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker run -v $(pwd):/data:ro mbologna/docker-tokei | awk '/Total/{print $4 + $5}'>temp.txt;
      cat temp.txt;
      curl -H "Content-Type:application/json" -H "X-Shiny-Token:$SHINY_TOKEN" -X POST -d '{"line":'$(cat temp.txt)', "name":"Shiny-Console"}' "https://shiny.kotori.moe/Repository/updateLines";
      rm -f temp.txt;
    fi