export const GET_KEY_PAIRS = 'GET_KEY_PAIRS';
export type GET_KEY_PAIRS = typeof GET_KEY_PAIRS;

export const GET_KEY_PAIRS_SUCCESS = 'GET_KEY_PAIRS_SUCCESS';
export type GET_KEY_PAIRS_SUCCESS = typeof GET_KEY_PAIRS_SUCCESS;

export const GET_KEY_PAIRS_FAILURE = 'GET_KEY_PAIRS_FAILURE';
export type GET_KEY_PAIRS_FAILURE = typeof GET_KEY_PAIRS_FAILURE;