export const GET_KEY_PAIRS = 'GET_KEY_PAIRS';
export type GET_KEY_PAIRS = typeof GET_KEY_PAIRS;

export const GET_KEY_PAIRS_SUCCESS = 'GET_KEY_PAIRS_SUCCESS';
export type GET_KEY_PAIRS_SUCCESS = typeof GET_KEY_PAIRS_SUCCESS;

export const GET_KEY_PAIRS_FAILURE = 'GET_KEY_PAIRS_FAILURE';
export type GET_KEY_PAIRS_FAILURE = typeof GET_KEY_PAIRS_FAILURE;

export const DELETE_KEY_PAIR = 'DELETE_KEY_PAIR';
export type DELETE_KEY_PAIR = typeof DELETE_KEY_PAIR;

export const DELETE_KEY_PAIR_SUCCESS = 'DELETE_KEY_PAIR_SUCCESS';
export type DELETE_KEY_PAIR_SUCCESS = typeof DELETE_KEY_PAIR_SUCCESS;

export const DELETE_KEY_PAIR_FAILURE = 'DELETE_KEY_PAIR_FAILURE';
export type DELETE_KEY_PAIR_FAILURE = typeof DELETE_KEY_PAIR_FAILURE;

export const CREATE_KEY_PAIR = 'CREATE_KEY_PAIR';
export type CREATE_KEY_PAIR = typeof CREATE_KEY_PAIR;

export const CREATE_KEY_PAIR_SUCCESS = 'CREATE_KEY_PAIR_SUCCESS';
export type CREATE_KEY_PAIR_SUCCESS = typeof CREATE_KEY_PAIR_SUCCESS;

export const CREATE_KEY_PAIR_FAILURE = 'CREATE_KEY_PAIR_FAILURE';
export type CREATE_KEY_PAIR_FAILURE = typeof CREATE_KEY_PAIR_FAILURE;

export const SHOW_CREATE_MODAL = 'SHOW_CREATE_MODAL';
export type SHOW_CREATE_MODAL = typeof SHOW_CREATE_MODAL;

export const CLOSE_CREATE_MODAL = 'CLOSE_CREATE_MODAL';
export type CLOSE_CREATE_MODAL = typeof CLOSE_CREATE_MODAL;