export const GET_CONFIG_LIST = 'GET_CONFIG_LIST';
export type GET_CONFIG_LIST = typeof GET_CONFIG_LIST;

export const GET_CONFIG_LIST_SUCCESS = 'GET_CONFIG_LIST_SUCCESS';
export type GET_CONFIG_LIST_SUCCESS = typeof GET_CONFIG_LIST_SUCCESS;

export const GET_CONFIG_LIST_FAILURE = 'GET_CONFIG_LIST_FAILURE';
export type GET_CONFIG_LIST_FAILURE = typeof GET_CONFIG_LIST_FAILURE;

export const SHOW_CREATE_CONFIG_MODAL = 'SHOW_CREATE_CONFIG_MODAL';
export type SHOW_CREATE_CONFIG_MODAL = typeof SHOW_CREATE_CONFIG_MODAL;

export const HIDE_CREATE_CONFIG_MODAL = 'HIDE_CREATE_CONFIG_MODAL';
export type HIDE_CREATE_CONFIG_MODAL = typeof HIDE_CREATE_CONFIG_MODAL;

export const CREATE_CONFIG = 'CREATE_CONFIG';
export type CREATE_CONFIG = typeof CREATE_CONFIG;

export const CREATE_CONFIG_SUCCESS = 'CREATE_CONFIG_SUCCESS';
export type CREATE_CONFIG_SUCCESS = typeof CREATE_CONFIG_SUCCESS;

export const CREATE_CONFIG_FAILURE = 'CREATE_CONFIG_FAILURE';
export type CREATE_CONFIG_FAILURE = typeof CREATE_CONFIG_FAILURE;

export const DELETE_CONFIG = 'DELETE_CONFIG';
export type DELETE_CONFIG = typeof DELETE_CONFIG;

export const DELETE_CONFIG_SUCCESS = 'DELETE_CONFIG_SUCCESS';
export type DELETE_CONFIG_SUCCESS = typeof DELETE_CONFIG_SUCCESS;

export const DELETE_CONFIG_FAILURE = 'DELETE_CONFIG_FAILURE';
export type DELETE_CONFIG_FAILURE = typeof DELETE_CONFIG_FAILURE;

export const SHOW_EDIT_CONFIG_MODAL = 'SHOW_EDIT_CONFIG_MODAL';
export type SHOW_EDIT_CONFIG_MODAL = typeof SHOW_EDIT_CONFIG_MODAL;

export const HIDE_EDIT_CONFIG_MODAL = 'HIDE_EDIT_CONFIG_MODAL';
export type HIDE_EDIT_CONFIG_MODAL = typeof HIDE_EDIT_CONFIG_MODAL;

export const EDIT_CONFIG = 'EDIT_CONFIG';
export type EDIT_CONFIG = typeof EDIT_CONFIG;

export const EDIT_CONFIG_SUCCESS = 'EDIT_CONFIG_SUCCESS';
export type EDIT_CONFIG_SUCCESS = typeof EDIT_CONFIG_SUCCESS;

export const EDIT_CONFIG_FAILURE = 'EDIT_CONFIG_FAILURE';
export type EDIT_CONFIG_FAILURE = typeof EDIT_CONFIG_FAILURE;