// Server/Node

export const GET_SERVER_LIST = 'GET_SERVER_LIST';
export type GET_SERVER_LIST = typeof GET_SERVER_LIST;

export const GET_SERVER_LIST_SUCCESS = 'GET_SERVER_LIST_SUCCESS';
export type GET_SERVER_LIST_SUCCESS = typeof GET_SERVER_LIST_SUCCESS;

export const GET_SERVER_LIST_FAILURE = 'GET_SERVER_LIST_FAILURE';
export type GET_SERVER_LIST_FAILURE = typeof GET_SERVER_LIST_FAILURE;

export const DELETE_SERVER = 'DELETE_SERVER';
export type DELETE_SERVER = typeof DELETE_SERVER;

export const DELETE_SERVER_SUCCESS = 'DELETE_SERVER_SUCCESS';
export type DELETE_SERVER_SUCCESS = typeof DELETE_SERVER_SUCCESS;

export const DELETE_SERVER_FAILURE = 'DELETE_SERVER_FAILURE';
export type DELETE_SERVER_FAILURE = typeof DELETE_SERVER_FAILURE;

export const ADD_SERVER = 'ADD_SERVER';
export type ADD_SERVER = typeof ADD_SERVER;

export const ADD_SERVER_SUCCESS = 'ADD_SERVER_SUCCESS';
export type ADD_SERVER_SUCCESS = typeof ADD_SERVER_SUCCESS;

export const ADD_SERVER_FAILURE = 'ADD_SERVER_FAILURE';
export type ADD_SERVER_FAILURE = typeof ADD_SERVER_FAILURE;

export const SHOW_CREATE_SERVER_MODAL = 'SHOW_CREATE_SERVER_MODAL';
export type SHOW_CREATE_SERVER_MODAL = typeof SHOW_CREATE_SERVER_MODAL;

export const CLOSE_CREATE_SERVER_MODAL = 'CLOSE_CREATE_SERVER_MODAL';
export type CLOSE_CREATE_SERVER_MODAL = typeof CLOSE_CREATE_SERVER_MODAL;