// Server/Node

export const GET_SERVER_LIST = 'GET_SERVER_LIST';
export type GET_SERVER_LIST = typeof GET_SERVER_LIST;

export const GET_SERVER_LIST_SUCCESS = 'GET_SERVER_LIST_SUCCESS';
export type GET_SERVER_LIST_SUCCESS = typeof GET_SERVER_LIST_SUCCESS;

export const GET_SERVER_LIST_FAILURE = 'GET_SERVER_LIST_FAILURE';
export type GET_SERVER_LIST_FAILURE = typeof GET_SERVER_LIST_FAILURE;