export const GET_IDENTITY_LIST = 'GET_IDENTITY_LIST';
export type GET_IDENTITY_LIST = typeof GET_IDENTITY_LIST;

export const GET_IDENTITY_LIST_SUCCESS = 'GET_IDENTITY_LIST_SUCCESS';
export type GET_IDENTITY_LIST_SUCCESS = typeof GET_IDENTITY_LIST_SUCCESS;

export const GET_IDENTITY_LIST_FAILURE = 'GET_IDENTITY_LIST_FAILURE';
export type GET_IDENTITY_LIST_FAILURE = typeof GET_IDENTITY_LIST_FAILURE;

export const SHOW_CREATE_IDENTITY_MODAL = 'SHOW_CREATE_IDENTITY_MODAL';
export type SHOW_CREATE_IDENTITY_MODAL = typeof SHOW_CREATE_IDENTITY_MODAL;

export const HIDE_CREATE_IDENTITY_MODAL = 'HIDE_CREATE_IDENTITY_MODAL';
export type HIDE_CREATE_IDENTITY_MODAL = typeof HIDE_CREATE_IDENTITY_MODAL;

export const CREATE_IDENTITY = 'CREATE_IDENTITY';
export type CREATE_IDENTITY = typeof CREATE_IDENTITY;

export const CREATE_IDENTITY_SUCCESS = 'CREATE_IDENTITY_SUCCESS';
export type CREATE_IDENTITY_SUCCESS = typeof CREATE_IDENTITY_SUCCESS;

export const CREATE_IDENTITY_FAILURE = 'CREATE_IDENTITY_FAILURE';
export type CREATE_IDENTITY_FAILURE = typeof CREATE_IDENTITY_FAILURE;

export const DELETE_IDENTITY = 'DELETE_IDENTITY';
export type DELETE_IDENTITY = typeof DELETE_IDENTITY;

export const DELETE_IDENTITY_SUCCESS = 'DELETE_IDENTITY_SUCCESS';
export type DELETE_IDENTITY_SUCCESS = typeof DELETE_IDENTITY_SUCCESS;

export const DELETE_IDENTITY_FAILURE = 'DELETE_IDENTITY_FAILURE';
export type DELETE_IDENTITY_FAILURE = typeof DELETE_IDENTITY_FAILURE;

export const SHOW_EDIT_IDENTITY_MODAL = 'SHOW_EDIT_IDENTITY_MODAL';
export type SHOW_EDIT_IDENTITY_MODAL = typeof SHOW_EDIT_IDENTITY_MODAL;

export const HIDE_EDIT_IDENTITY_MODAL = 'HIDE_EDIT_IDENTITY_MODAL';
export type HIDE_EDIT_IDENTITY_MODAL = typeof HIDE_EDIT_IDENTITY_MODAL;

export const EDIT_IDENTITY = 'EDIT_IDENTITY';
export type EDIT_IDENTITY = typeof EDIT_IDENTITY;

export const EDIT_IDENTITY_SUCCESS = 'EDIT_IDENTITY_SUCCESS';
export type EDIT_IDENTITY_SUCCESS = typeof EDIT_IDENTITY_SUCCESS;

export const EDIT_IDENTITY_FAILURE = 'EDIT_IDENTITY_FAILURE';
export type EDIT_IDENTITY_FAILURE = typeof EDIT_IDENTITY_FAILURE;