export const GET_SPIDER_LIST = 'GET_SPIDER_LIST';
export type GET_SPIDER_LIST = typeof GET_SPIDER_LIST;

export const GET_SPIDER_LIST_SUCCESS = 'GET_SPIDER_LIST_SUCCESS';
export type GET_SPIDER_LIST_SUCCESS = typeof GET_SPIDER_LIST_SUCCESS;

export const GET_SPIDER_LIST_FAILURE = 'GET_SPIDER_LIST_FAILURE';
export type GET_SPIDER_LIST_FAILURE = typeof GET_SPIDER_LIST_FAILURE;