export const GET_SPIDER_LIST = 'GET_SPIDER_LIST';
export type GET_SPIDER_LIST = typeof GET_SPIDER_LIST;

export const GET_SPIDER_LIST_SUCCESS = 'GET_SPIDER_LIST_SUCCESS';
export type GET_SPIDER_LIST_SUCCESS = typeof GET_SPIDER_LIST_SUCCESS;

export const GET_SPIDER_LIST_FAILURE = 'GET_SPIDER_LIST_FAILURE';
export type GET_SPIDER_LIST_FAILURE = typeof GET_SPIDER_LIST_FAILURE;

export const DELETE_SPIDER = 'DELETE_SPIDER';
export type DELETE_SPIDER = typeof DELETE_SPIDER;

export const DELETE_SPIDER_SUCCESS = 'DELETE_SPIDER_SUCCESS';
export type DELETE_SPIDER_SUCCESS = typeof DELETE_SPIDER_SUCCESS;

export const DELETE_SPIDER_FAILURE = 'DELETE_SPIDER_FAILURE';
export type DELETE_SPIDER_FAILURE = typeof DELETE_SPIDER_FAILURE;

export const UPDATE_FREQUENCY_SHOW_MODAL = 'UPDATE_FREQUENCY_SHOW_MODAL';
export type UPDATE_FREQUENCY_SHOW_MODAL = typeof UPDATE_FREQUENCY_SHOW_MODAL;

export const UPDATE_FREQUENCY_START = 'UPDATE_FREQUENCY_START';
export type UPDATE_FREQUENCY_START = typeof UPDATE_FREQUENCY_START;

export const UPDATE_FREQUENCY_CANCEL = 'UPDATE_FREQUENCY_CANCEL';
export type UPDATE_FREQUENCY_CANCEL = typeof UPDATE_FREQUENCY_CANCEL;

export const UPDATE_FREQUENCY_SUCCESS = 'UPDATE_FREQUENCY_SUCCESS';
export type UPDATE_FREQUENCY_SUCCESS = typeof UPDATE_FREQUENCY_SUCCESS;

export const UPDATE_FREQUENCY_FAILURE = 'UPDATE_FREQUENCY_FAILURE';
export type UPDATE_FREQUENCY_FAILURE = typeof UPDATE_FREQUENCY_FAILURE;

export const EDIT_SPIDER_SHOW_MODAL = 'EDIT_SPIDER_SHOW_MODAL';
export type EDIT_SPIDER_SHOW_MODAL = typeof EDIT_SPIDER_SHOW_MODAL;

export const EDIT_SPIDER_CANCEL = 'EDIT_SPIDER_CANCEL';
export type EDIT_SPIDER_CANCEL = typeof EDIT_SPIDER_CANCEL;

export const EDIT_SPIDER_START = 'EDIT_SPIDER_START';
export type EDIT_SPIDER_START = typeof EDIT_SPIDER_START;

export const EDIT_SPIDER_SUCCESS = 'EDIT_SPIDER_SUCCESS';
export type EDIT_SPIDER_SUCCESS = typeof EDIT_SPIDER_SUCCESS;

export const EDIT_SPIDER_FAILURE = 'EDIT_SPIDER_FAILURE';
export type EDIT_SPIDER_FAILURE = typeof EDIT_SPIDER_FAILURE;