export const GET_SPIDER_LIST = 'GET_SPIDER_LIST';
export type GET_SPIDER_LIST = typeof GET_SPIDER_LIST;

export const GET_SPIDER_LIST_SUCCESS = 'GET_SPIDER_LIST_SUCCESS';
export type GET_SPIDER_LIST_SUCCESS = typeof GET_SPIDER_LIST_SUCCESS;

export const GET_SPIDER_LIST_FAILURE = 'GET_SPIDER_LIST_FAILURE';
export type GET_SPIDER_LIST_FAILURE = typeof GET_SPIDER_LIST_FAILURE;

export const DELETE_SPIDER = 'DELETE_SPIDER';
export type DELETE_SPIDER = typeof DELETE_SPIDER;

export const DELETE_SPIDER_SUCCESS = 'DELETE_SPIDER_SUCCESS';
export type DELETE_SPIDER_SUCCESS = typeof DELETE_SPIDER_SUCCESS;

export const DELETE_SPIDER_FAILURE = 'DELETE_SPIDER_FAILURE';
export type DELETE_SPIDER_FAILURE = typeof DELETE_SPIDER_FAILURE;