export const LOGIN = 'LOGIN';
export type LOGIN = typeof LOGIN;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export type LOGIN_FAILURE = typeof LOGIN_FAILURE;

// Dashboard
export const RAISE_ERROR = 'RAISE_ERROR';
export type RAISE_ERROR = typeof RAISE_ERROR;

// Dashboard/Overview

export const GET_STATISTICS = 'GET_STATISTICS';
export type GET_STATISTICS = typeof GET_STATISTICS;

export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export type GET_STATISTICS_SUCCESS = typeof GET_STATISTICS_SUCCESS;

export const GET_STATISTIC_FAILURE = 'GET_STATISTICS_FAILURE';
export type GET_STATISTIC_FAILURE = typeof GET_STATISTIC_FAILURE;

// Dashboard/Realtime

export const GET_RECENT_EVENTS = 'GET_RECENT_EVENTS';
export type GET_RECENT_EVENTS = typeof GET_RECENT_EVENTS;

export const GET_RECENT_EVENTS_SUCCESS = 'GET_RECENT_EVENTS_SUCCESS';
export type GET_RECENT_EVENTS_SUCCESS = typeof GET_RECENT_EVENTS_SUCCESS;

export const GET_RECENT_EVENTS_FAILURE = 'GET_RECENT_EVENTS_FAILURE';
export type GET_RECENT_EVENTS_FAILURE = typeof GET_RECENT_EVENTS_FAILURE;

export const ADD_RECENT_EVENT = 'ADD_RECENT_EVENT';
export type ADD_RECENT_EVENT = typeof ADD_RECENT_EVENT;

export const ADD_JOB = 'ADD_JOB';
export type ADD_JOB = typeof ADD_JOB;

export const UPDATE_JOB = 'UPDATE_JOB';
export type UPDATE_JOB = typeof UPDATE_JOB;