// Dashboard/Overview

export const GET_STATISTICS = 'GET_STATISTICS';
export type GET_STATISTICS = typeof GET_STATISTICS;

export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export type GET_STATISTICS_SUCCESS = typeof GET_STATISTICS_SUCCESS;

export const GET_STATISTIC_FAILURE = 'GET_STATISTICS_FAILURE';
export type GET_STATISTIC_FAILURE = typeof GET_STATISTIC_FAILURE;