export const GET_ACCOUNT_LIST = 'GET_ACCOUNT_LIST';
export type GET_ACCOUNT_LIST = typeof GET_ACCOUNT_LIST;

export const GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS';
export type GET_ACCOUNT_LIST_SUCCESS = typeof GET_ACCOUNT_LIST_SUCCESS;

export const GET_ACCOUNT_LIST_FAILURE = 'GET_ACCOUNT_LIST_FAILURE';
export type GET_ACCOUNT_LIST_FAILURE = typeof GET_ACCOUNT_LIST_FAILURE;

export const SHOW_CREATE_ACCOUNT_MODAL = 'SHOW_CREATE_ACCOUNT_MODAL';
export type SHOW_CREATE_ACCOUNT_MODAL = typeof SHOW_CREATE_ACCOUNT_MODAL;

export const HIDE_CREATE_ACCOUNT_MODAL = 'HIDE_CREATE_ACCOUNT_MODAL';
export type HIDE_CREATE_ACCOUNT_MODAL = typeof HIDE_CREATE_ACCOUNT_MODAL;

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export type CREATE_ACCOUNT = typeof CREATE_ACCOUNT;

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export type CREATE_ACCOUNT_SUCCESS = typeof CREATE_ACCOUNT_SUCCESS;

export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';
export type CREATE_ACCOUNT_FAILURE = typeof CREATE_ACCOUNT_FAILURE;

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export type DELETE_ACCOUNT = typeof DELETE_ACCOUNT;

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export type DELETE_ACCOUNT_SUCCESS = typeof DELETE_ACCOUNT_SUCCESS;

export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export type DELETE_ACCOUNT_FAILURE = typeof DELETE_ACCOUNT_FAILURE;

export const SHOW_EDIT_ACCOUNT_MODAL = 'SHOW_EDIT_ACCOUNT_MODAL';
export type SHOW_EDIT_ACCOUNT_MODAL = typeof SHOW_EDIT_ACCOUNT_MODAL;

export const HIDE_EDIT_ACCOUNT_MODAL = 'HIDE_EDIT_ACCOUNT_MODAL';
export type HIDE_EDIT_ACCOUNT_MODAL = typeof HIDE_EDIT_ACCOUNT_MODAL;

export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export type EDIT_ACCOUNT = typeof EDIT_ACCOUNT;

export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';
export type EDIT_ACCOUNT_SUCCESS = typeof EDIT_ACCOUNT_SUCCESS;

export const EDIT_ACCOUNT_FAILURE = 'EDIT_ACCOUNT_FAILURE';
export type EDIT_ACCOUNT_FAILURE = typeof EDIT_ACCOUNT_FAILURE;