export const GET_PUSH_HISTORY = 'GET_PUSH_HISTORY';
export type GET_PUSH_HISTORY = typeof GET_PUSH_HISTORY;

export const GET_PUSH_HISTORY_SUCCESS = 'GET_PUSH_HISTORY_SUCCESS';
export type GET_PUSH_HISTORY_SUCCESS = typeof GET_PUSH_HISTORY_SUCCESS;

export const GET_PUSH_HISTORY_FAILURE = 'GET_PUSH_HISTORY_FAILURE';
export type GET_PUSH_HISTORY_FAILURE = typeof GET_PUSH_HISTORY_FAILURE;