export const GET_RULE_LIST = 'GET_RULE_LIST';
export type GET_RULE_LIST = typeof GET_RULE_LIST;

export const GET_RULE_LIST_SUCCESS = 'GET_RULE_LIST_SUCCESS';
export type GET_RULE_LIST_SUCCESS = typeof GET_RULE_LIST_SUCCESS;

export const GET_RULE_LIST_FAILURE = 'GET_RULE_LIST_FAILURE';
export type GET_RULE_LIST_FAILURE = typeof GET_RULE_LIST_FAILURE;

export const SHOW_CREATE_RULE_MODAL = 'SHOW_CREATE_RULE_MODAL';
export type SHOW_CREATE_RULE_MODAL = typeof SHOW_CREATE_RULE_MODAL;

export const HIDE_CREATE_RULE_MODAL = 'HIDE_CREATE_RULE_MODAL';
export type HIDE_CREATE_RULE_MODAL = typeof HIDE_CREATE_RULE_MODAL;

export const CREATE_RULE = 'CREATE_RULE';
export type CREATE_RULE = typeof CREATE_RULE;

export const CREATE_RULE_SUCCESS = 'CREATE_RULE_SUCCESS';
export type CREATE_RULE_SUCCESS = typeof CREATE_RULE_SUCCESS;

export const CREATE_RULE_FAILURE = 'CREATE_RULE_FAILURE';
export type CREATE_RULE_FAILURE = typeof CREATE_RULE_FAILURE;

export const DELETE_RULE = 'DELETE_RULE';
export type DELETE_RULE = typeof DELETE_RULE;

export const DELETE_RULE_SUCCESS = 'DELETE_RULE_SUCCESS';
export type DELETE_RULE_SUCCESS = typeof DELETE_RULE_SUCCESS;

export const DELETE_RULE_FAILURE = 'DELETE_RULE_FAILURE';
export type DELETE_RULE_FAILURE = typeof DELETE_RULE_FAILURE;

export const SHOW_EDIT_RULE_MODAL = 'SHOW_EDIT_RULE_MODAL';
export type SHOW_EDIT_RULE_MODAL = typeof SHOW_EDIT_RULE_MODAL;

export const HIDE_EDIT_RULE_MODAL = 'HIDE_EDIT_RULE_MODAL';
export type HIDE_EDIT_RULE_MODAL = typeof HIDE_EDIT_RULE_MODAL;

export const EDIT_RULE = 'EDIT_RULE';
export type EDIT_RULE = typeof EDIT_RULE;

export const EDIT_RULE_SUCCESS = 'EDIT_RULE_SUCCESS';
export type EDIT_RULE_SUCCESS = typeof EDIT_RULE_SUCCESS;

export const EDIT_RULE_FAILURE = 'EDIT_RULE_FAILURE';
export type EDIT_RULE_FAILURE = typeof EDIT_RULE_FAILURE;